### ISSUE TITLE
Multiple conformsTo values

### ISSUE THREAD

**Issue by beepsoft** [kit-data-manager/ro-crate-java#105]
First of all, thanks for the library!

Currently the library targets RO-Crate 1.1 and the current behaviour regarding the use of `conformsTo` is implemented according to this:

https://www.researchobject.org/ro-crate/1.1/root-data-entity.html#finding-the-root-data-entity

```
if the conformsTo property is a URI that starts with https://w3id.org/ro/crate/
...
```

This is implemented here and expects to have a single object for `conformsTo` with an `@id` value:

https://github.com/kit-data-manager/ro-crate-java/blob/6c9f30ddf6bff9c53d98d72ee0e85cd21b145713/src/main/java/edu/kit/datamanager/ro_crate/reader/RoCrateReader.java#L121-L123

In the proposed 1.2 draft the  `conformsTo` may be an array of such objects.

https://www.researchobject.org/ro-crate/1.2-DRAFT/profiles.html

```
It is valid for a crate to conform to multiple profiles, in which case conformsTo is an unordered array.
```

We try to use this multiple profile support of RO-Crate 1.2 in our project, so it would be great if you could support multiple  `conformsTo` values. Currently, it throws as error because the ```type.get("@id").asText()``` will fail when `type` is an array.

**Comment by Pfeil** [comment]
Thank you for this issue. I'd like to include this feature soon. As this kind of would be a breaking change to 1.1, we need to take some considerations, though.

Some implementation notes:

- The best will probably be for the reader to recognize the version and then deserialize a different context object for the new version.
- For the writer there should not be much of a difference. But we should consider offering the possibility to upgrade to newer versions on export. Not sure if this can be done always fully automatically and if it should be the default, though.
- The examples on the linked 1.2 draft seem inconsistent with the [1.2 File descriptor](https://www.researchobject.org/ro-crate/1.2-DRAFT/root-data-entity.html#ro-crate-metadata-file-descriptor), where it states the ro-crate spec should be referenced (although the should may be the reason), meaning in this case ther should be at least two entries. I suggest to make it the default that the ro-crate specification is referenced in any case (as it is now). This means that, if someone really does not want to include the RO-Crate specification as in the examples, it will take at least one additional line of code. But I'll need to read through that in detail, maybe I missed something.

**Comment by beepsoft** [comment]
Thanks for taking this into consideration!

I don't know about the status of version 1.2, but as this is a draft, there could be inconsistencies. My interpretation would be that `conformsTo` maybe an array, but has to include at least one object referencing `https://w3id.org/ro/crate/...`, or it maybe a single object in which case it is the one that is referencing `https://w3id.org/ro/crate/...`.

**Comment by Pfeil** [comment]
I shortly looked into it today. My plan is to have a branch soon which you may test (I'll see if we can publish beta releases to include/test them easier in projects). I hope to provide a first solution until next week.

**Comment by Pfeil** [comment]
I am sorry for the large delay. I released two versions today. One being a simple update of the dependencies, nothing new here. The other should contain all basic functionality to work with the "new" conformsTo array: [v1.1.0-rc.1](https://github.com/kit-data-manager/ro-crate-java/releases/tag/v1.1.0-rc.1)

The readme now points out [a few tests where the read- write and modification process is being tested/demonstrated](https://github.com/kit-data-manager/ro-crate-java#ro-crate-specification-compatibility). The concept has not changed a lot. There is a new builder which allows functionality from draft-specifications. You can use it to create or modify crates. It will update the version by itself if you use one of the functionalities.

If something does not work out for you, please return to this issue or open a new one. Otherwise, I plan to release the real 1.1.0 in a few weeks, depending on feedback coming in. Thanks a lot!

**Comment by beepsoft** [comment]
Thanks, @Pfeil, we will check it out next week and give you feedback.

**Comment by atniph** [comment]
@Pfeil Thanks for your work, everything seems to be working fine.
