### ISSUE TITLE
Missing support for provenance elements

### ISSUE THREAD

**Issue by ThomasJejkal** [kit-data-manager/ro-crate-java#137]
It seems that provenance elements defined in the [RO-Crate specification](https://www.researchobject.org/ro-crate/1.1/provenance.html) are not supported. Thus, it is not possible to describe the provenance of data, e.g., CreateAction, UpdateAction, used instruments etc.

**Comment by Pfeil** [comment]
Has already been fixed in b1966636a2c309b2c8fdf5a7aa9b3486aa6481bf. I think it should have been possible in beforehand, but with more fiddling, as there was no helper class or builder. The fix is a good idea. Probably, the test / usage example could look more ergonomic (more consistent regarding other builders). I will let the issue open until I was able to take a closer look.
