### ISSUE TITLE
Removing urls/key-value pairs from the context is not supported

### ISSUE THREAD

**Issue by Code42Cate** [kit-data-manager/ro-crate-java#37]
We can already add Urls and key-value pairs to the context, but there is no way to delete them from existing crates. (Also no way to read them besides raw JSON, but that's a different issue)

I propose adding these two functions to the RoCrate:
```java
public void deleteUrlFromContext(String Url)
public void deleteValuePairFromContext(String key)
```
I am going to make a PR for this later today.

**Comment by Code42Cate** [comment]
The behaviour of `deleteUrlFromContext` is a bit more complex than I initially thought. `addToContextFromUrl` is actually downloading the key-value pairs from the url and adding the url as well as key-value pairs to the context. Should `deleteUrlFromContext` only remove the url or also try to remove the key-value pairs that were fetched from the url? I would say that just deleting the url is good enough for now, what do you think? @Pfeil

**Comment by Code42Cate** [comment]
`deleteValuePairFromContext` PR is ready, `deleteUrlFromContext` is coming in a separate one when I know how we want to handle this

**Comment by Pfeil** [comment]
Not sure about `deleteURLFromContext`. Some thoughts:

- If I remember correctly, the reason the pairs are extracted is that this was either recommended or enables / simplifies validation.
- Assume we would delete the pairs contained in the URL, which we want to delete. Then we would have to check if the pairs are not in another URL or (and this is critical) inserted implicitly. Checking the latter ase is not really possible, and we do not want to remove pairs when they are not in a URL (because maybe they are, but the machine does not know due to missing machine readability).
- I think it does not make sense trying to remember how it was before that, because when reading a crate, we do not have this information.
- If we would have a strategy different from not touching the pairs, we could pass it as a parameter. But I do not see one.
- For now, I think simply removing the URL is the best thing. We could use the return values to return the pairs we were able to extract from the URL as a list (which may be empty, avoid null?). The user then may deal with it. It would limit the possibilities of error handling, so probably we should use exceptions for that. Or a result type... but that is not very java-ish, unfortunately.
- I think it should not be possible to remove the default context of RO-Crate. Instead, we may have a function later to replace it with a new version or so. Or a function that upgrades the crate spec version overall, not sure about that.

**Comment by Code42Cate** [comment]
Good points, the pairs are extracted to make the crates “archivable”, according to the specification (14.2 RO-Crate JSON-LD Context)

Regarding your last point, I don't think the default context is required. This is the only relevant part I found in the specification (4.1 RO-Crate Metadata File): 

> The RO-Crate JSON-LD SHOULD use the RO-Crate JSON-LD Context
https://w3id.org/ro/crate/1.1/context by reference.

I am going to implement the simplest form of Context URL deletion and make a PR.
