### ISSUE TITLE
It is possible to create unreferenced data entites, resulting in invalid crates

### ISSUE THREAD

**Issue by Code42Cate** [kit-data-manager/ro-crate-java#49]
According to the specification, every Data Entity **MUST** be linked to the Root Data Entity:

> Where files and folders are represented as Data Entities in the RO-Crate JSON-LD, these MUST be linked to, either directly or indirectly, from the [Root Data Entity](https://www.researchobject.org/ro-crate/1.1/root-data-entity.html) using the [hasPart](http://schema.org/hasPart) property.

Adding a Data Entity like this is valid according to the library:
```java
crate.addDataEntity(new DataSetEntity.DataSetBuilder().setId("./some_file").build(), false);
```
Now at this point, the crate is not valid. If you add a DataSetEntity that has a `hasPart` property linking to `./some_file` and the Root Data Entity has a `hasPart` property linking to this DataSetEntity it would be valid again.

**Comment by Pfeil** [comment]
For clarification:

- The builder's `builder.addDataEntity(DataEntity)` does add it correctly.
- The crate's `crate.addDataEntity` does this only optionally, with `crate.addDataEntity(DataEntity, true)`. It does not if the second parameter is false or without it (`crate.addDataEntity(DataEntity)`).

At first glance, it seems to be used with the boolean being false only once in the whole code, at the RoCrateReader, for each DataEntity. Currently, I do not understand why, but I assume that it is because in this case, it is already inside. I think we should:

- [ ] change the default from "not being added" to "being added" at least.
- [ ] But ideally, we should figure out if we can remove this "feature" completely in the end. For example, if this is about not adding something twice, we may use a set in the background (this is already the case!) and simply add it anyway. It should not change anything, then.

**Comment by Code42Cate** [comment]
🎉
